### ISSUE TITLE
Question about Algorithm 1

### ISSUE THREAD

**Issue by alimohammadiamirhossein** [inbarhub/DDPM_inversion#15]
![image](https://github.com/user-attachments/assets/dcf26555-9b6e-450d-8c3f-d3a3c4162e76)

Hi, I have a question about this part of the paper. You wrote:
z_t = [x_(t-1) - mu_hat_t(x_t)]/sigma_t
x_(t-1) = mu_hat_t(x_t) + sigma_t*z_t 
which is equal to 
mu_hat_t(x_t) + sigma_t*[x_(t-1) - mu_hat_t(x_t)]/sigma_t = mu_hat_t(x_t)+ [x_(t-1) - mu_hat_t(x_t)] = x_(t-1) 

Could you explain this part to me? I feel like I might be missing something.

**Comment by inbarhub** [comment]
Hi, 

I can see how this might be confusing. Yes, theoretically, the second line `mu_hat_t_{x_t} + sigma_t*z_t` is equal to `x_{t-1}`.
 
In practice, however, when calculating `mu_hat_t_{x_t} + sigma_t*z_t` it may deviate slightly from `x_{t-1}` that we aim to reconstruct, especially with a small number of steps and large CFG.

To avoid this, we use the newly calculated `x_{t-1}` instead of the one obtained from the initial forward process.

You can also observe the effect of this numerical drift and the correction in our supplementary material, Section B.
