### ISSUE TITLE
about the Color manipulation.

### ISSUE THREAD

**Issue by segatecm** [inbarhub/DDPM_inversion#3]
Hi @inbarhub , thanks for your greate work.
Can you give some code about the Color manipulation in your paper?
Thanks again!

**Comment by inbarhub** [comment]
Since the color manipulation is done in the pixel-space mode (and not in the latent space as done with the text), we won't publish the entire code. But here is the part of the code we use:
From the given mask we created a binary mask which is just applying a threshold. Then, for every t, we changed z[t] as follows:
x0_prediction = (out["pred_xstart"]+1)/2 #the x_0 prediction in the current timestep after changing it to be in [0,1] range
z[t] = (1-mask_binary)*z[t]+mask_binary*(z[t]+alpha*(mask.unsqueeze(0)-x0_prediction)) #color-mask

**Comment by Tonniia** [comment]
will this changed z[t] affect the updating of x[t-1]？
